class Main {
  public static void main(String[] args) {
    try {
    int a=50/0; // ArithmeticException 
    } catch (ArithmeticException e) {
    System.out.println("Exception thrown :" + e);
    }
    System.out.println("Out of the block");
    }
}
